# Generated by Django 4.1 on 2022-09-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chunked_upload', '0004_chunkedupload_codec_name_chunkedupload_type_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkedupload',
            name='type_extension',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
