# Generated by Django 4.1 on 2022-09-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chunked_upload', '0005_chunkedupload_type_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkedupload',
            name='height',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='width',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
